# Generated by Django 5.2.7 on 2025-11-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_dataupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataUpload',
        ),
    ]
